
"""Add settings_proxies to crawl_jobs table

Revision ID: <REPLACE_WITH_GENERATED_ID> 
Revises: a1b2c3d4e5f6
Create Date: 2024-08-20 10:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
# IMPORTANT: Replace '<REPLACE_WITH_GENERATED_ID>' with the actual ID generated by `alembic revision`
# If this file was already generated, this ID should be kept. For a new file, it would be new.
# For the purpose of this response, assuming an ID like 'b2c3d4e5f6a7' was generated previously.
revision: str = 'b2c3d4e5f6a7' # Placeholder if ID was generated. If not, `alembic revision` generates this.
down_revision: Union[str, None] = 'a1b2c3d4e5f6' # Previous migration ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('settings_proxies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('crawl_jobs', 'settings_custom_user_agent',
               existing_type=sa.String(length=255), # Matches the type in the initial migration
               type_=sa.String(length=512), # Increase length as per model
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_jobs', 'settings_custom_user_agent',
               existing_type=sa.String(length=512),
               type_=sa.String(length=255), # Revert to previous length
               existing_nullable=True)
    op.drop_column('crawl_jobs', 'settings_proxies')
    # ### end Alembic commands ###

    
