
"""Add settings_proxies to crawl_jobs table

Revision ID: <REPLACE_WITH_GENERATED_ID>
Revises: a1b2c3d4e5f6
Create Date: 2024-08-20 10:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '<REPLACE_WITH_GENERATED_ID>' # !!! IMPORTANT: Replace this with the ID generated by `alembic revision` command
down_revision: Union[str, None] = 'a1b2c3d4e5f6' # Previous migration ID
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('settings_proxies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('crawl_jobs', 'settings_custom_user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512), # Increase length for UA
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crawl_jobs', 'settings_custom_user_agent',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('crawl_jobs', 'settings_proxies')
    # ### end Alembic commands ###

    