
"""Initial migration with all current models

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2024-08-16 10:00:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('settings_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings_file_extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings_seed_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings_search_dorks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings_crawl_depth', sa.Integer(), nullable=True),
    sa.Column('settings_respect_robots_txt', sa.Boolean(), nullable=True),
    sa.Column('settings_request_delay_seconds', sa.Float(), nullable=True),
    sa.Column('settings_use_search_engines', sa.Boolean(), nullable=True),
    sa.Column('settings_max_results_per_dork', sa.Integer(), nullable=True),
    sa.Column('settings_max_concurrent_requests_per_domain', sa.Integer(), nullable=True),
    sa.Column('settings_custom_user_agent', sa.String(length=255), nullable=True), # Initial length, will be updated by next migration
    sa.Column('settings_schedule_type', sa.String(length=20), nullable=True),
    sa.Column('settings_schedule_cron_expression', sa.String(length=100), nullable=True),
    sa.Column('settings_schedule_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_schedule_timezone', sa.String(length=50), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_last_run_at'), 'crawl_jobs', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_name'), 'crawl_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_next_run_at'), 'crawl_jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()),
    sa.Column('role', sa.String(length=50), nullable=True, server_default='user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    
    op.create_table('downloaded_files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('keywords_found', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_found', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('crawl_job_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloaded_files_checksum_md5'), 'downloaded_files', ['checksum_md5'], unique=False)
    op.create_index(op.f('ix_downloaded_files_file_type'), 'downloaded_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_downloaded_files_file_url'), 'downloaded_files', ['file_url'], unique=False)
    op.create_index(op.f('ix_downloaded_files_source_url'), 'downloaded_files', ['source_url'], unique=False)
    
    op.create_table('user_preferences',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('default_items_per_page', sa.Integer(), nullable=False, server_default='10'),
    sa.Column('receive_email_notifications', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_downloaded_files_source_url'), table_name='downloaded_files')
    op.drop_index(op.f('ix_downloaded_files_file_url'), table_name='downloaded_files')
    op.drop_index(op.f('ix_downloaded_files_file_type'), table_name='downloaded_files')
    op.drop_index(op.f('ix_downloaded_files_checksum_md5'), table_name='downloaded_files')
    op.drop_table('downloaded_files')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_next_run_at'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_name'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_last_run_at'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###

